### ISSUE TITLE
AWS para Firemonkey (Android / iOS)

### ISSUE THREAD

**Issue by hebrao** [mdbs99/aws#12]
Brilhante trabalho!
Algum dia pensam em deixar a "lib" compatível com Firemonkey para mobile?

**Comment by mdbs99** [comment]
Hoje só é compilável no FreePascal, porém não é muito difícil portar para o Delphi.
Colaboradores para fazer esses testes "cross-compiler" são bem vindos.

**Comment by mdbs99** [comment]
@hebrao sei agora que o Delphi desde a versão XE2 já tem uma lib para Amazon S3. Essa lib não funciona no mobile?

Estou perguntando pois agora tenho interesse em tornar esse projeto compatível com Delphi... se valer a pena.

**Comment by hebrao** [comment]
@mdbs99 a lib nativa do delphi funciona muito bem no S3. Consegui resolver meu problema!
