### ISSUE TITLE
Error: function header doesn't match the previous declaration "SetProperty"

### ISSUE THREAD

**Issue by tedsmith** [mdbs99/AWS#21]
Hi

This package looks ideal for my uses, and I am keen to try it out. But for info, after adding the Synapase package to Lazarus 2.0.10 with FPC 3.2.0, and attempting to install this package, I get this : 

"syncommons.pas(12605,14) Error: function header doesn't match the previous declaration "SetProperty(const tvardata;const AnsiString;const tvardata):Boolean;" (which refers to this package) and also 

"variants.pp(4175,33) Error: Found declaration: SetProperty(var tvardata;const AnsiString;const tvardata):Boolean;" which refers to the declaration in FPC. 

Not sure if this is something I am doing wrong or have configured wrong. Or whether the package needs tweaking for the 2020 versions of FPC and Lazarus? 

Many thanks again.

**Comment by tedsmith** [comment]
This turned out to be related to Synapse lib, and not this AWS lib. I had to make some changes to that to enable usage is all. 

Changing the declaration to virtual as below seems to have enabled compilation, along with a couple of compiler based tweaks re  Ansi2UnicodeMoveProc (i.e. the ifdef meant wrong number of parameters on Linux, so removed the compiler dirs and all compiles). 

```
    function SetProperty(const V: TVarData; const Name: string;
      const Value: TVarData): Boolean; virtual; 
```
and updated Ansi2UnicodeMoveProc to :
```
widestringmanager.Ansi2UnicodeMoveProc(Source,
      fCodePage,tmp,SourceChars);  
```

**Comment by mdbs99** [comment]
@tedsmith sorry my delay. I was "off" for a long... and I didn't receive those issues by email. Sorry.

**Comment by tedsmith** [comment]
No problem at all. Same for me with my projects - I often don't see them until later.

**Comment by mdbs99** [comment]
Covid has changed many things... anyway.
I need to update this project, thanks.
