### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by clusterdevm** [mdbs99/AWS#23]
on install package give this message , i'm using lazarus 

syncommons.pas(12605,14) Error: function header doesn't match the previous declaration "SetProperty(const tvardata;const AnsiString;const tvardata):Boolean;"

**Comment by tedsmith** [comment]
see https://github.com/mdbs99/aws/issues/21

**Comment by mdbs99** [comment]
@tedsmith thanks.

@clusterdevm mORMot is in development (V2) and I will update AWS when Arnaud finished his work. Until there, please follow Ted's tip or use a newer version of mORMot 1.
